#!/usr/bin/env swift

import Foundation

// Usage: swift build_secrets.swift <env_file_path> <output_swift_file_path>

guard CommandLine.arguments.count == 3 else {
    print("Usage: build_secrets.swift <env_file> <output_file>")
    exit(1)
}

let envPath = CommandLine.arguments[1]
let outputPath = CommandLine.arguments[2]

// Read .env file and parse KEY = VALUE pairs
let contents = try String(contentsOfFile: envPath, encoding: .utf8)
var secrets: [(key: String, value: String)] = []

for line in contents.components(separatedBy: .newlines) {
    let trimmed = line.trimmingCharacters(in: .whitespaces)
    if trimmed.isEmpty || trimmed.hasPrefix("#") { continue }
    let parts = trimmed.split(separator: "=", maxSplits: 1)
    guard parts.count == 2 else { continue }
    let key = parts[0].trimmingCharacters(in: .whitespaces)
    let value = parts[1].trimmingCharacters(in: .whitespaces)
    secrets.append((key: key, value: value))
}

// Generate a random XOR key at least as long as the longest secret
let maxLength = secrets.map(\.value.utf8.count).max() ?? 0
var keyBytes = [UInt8](repeating: 0, count: maxLength)
for i in 0..<maxLength {
    keyBytes[i] = UInt8.random(in: 1...255)
}
let keyBase64 = Data(keyBytes).base64EncodedString()

// XOR-encrypt each secret value
func encrypt(_ text: String, with key: [UInt8]) -> String {
    let textBytes = Array(text.utf8)
    var encrypted = [UInt8]()
    for (i, byte) in textBytes.enumerated() {
        encrypted.append(byte ^ key[i % key.count])
    }
    return Data(encrypted).base64EncodedString()
}

// Generate Swift source
var swift = """
// Auto-generated by build_secrets.swift — DO NOT EDIT
// Regenerated on every build with a fresh random key

import Foundation

enum BuildConfig {

"""

for secret in secrets {
    let encrypted = encrypt(secret.value, with: keyBytes)
    let camelCase = secret.key
        .lowercased()
        .split(separator: "_")
        .enumerated()
        .map { $0.offset == 0 ? String($0.element) : $0.element.prefix(1).uppercased() + $0.element.dropFirst() }
        .joined()
    swift += "    static let \(camelCase) = _decode(\"\(encrypted)\")\n"
}

swift += """

    private static let _key = Data(base64Encoded: "\(keyBase64)")!

    private static func _decode(_ secret: String) -> String {
        guard let data = Data(base64Encoded: secret) else { return "" }
        var result = [UInt8]()
        for (i, byte) in data.enumerated() {
            result.append(byte ^ _key[i % _key.count])
        }
        return String(bytes: result, encoding: .utf8) ?? ""
    }
}
"""

try swift.write(toFile: outputPath, atomically: true, encoding: .utf8)
print("Generated \(outputPath) with \(secrets.count) secrets")
